/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package one.chest

import groovy.transform.CompileDynamic
import groovy.transform.CompileStatic
import org.gradle.api.GradleException
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.publish.maven.MavenPublication

@CompileStatic
class MavenPublishPlugin implements Plugin<Project> {

    void apply(Project project) {
        project.apply plugin: "maven-publish"
        project.extensions.create("publish", MavenPublishExtension)

        project.afterEvaluate {
            configurePublishing(project);
        }
    }

    @CompileDynamic
    void configurePublishing(Project project) {
        project.with {
            // GRADLE DSL
            publishing {
                repositories {
                    maven {
                        String usernameStr = extractUsername(project)
                        String passwordStr = extractPassword(project)
                        if (usernameStr && passwordStr) {
                            credentials {
                                username usernameStr
                                password passwordStr
                            }
                        }
                        url = project.extensions.publish.repository.url ?: project.property("publish.repository.url")
                        mavenContent {
                            releasesOnly()
                        }
                    }
                }

                publications {
                    maven(MavenPublication) {
                        groupId = project.extensions.publish.groupId ?: project.group
                        artifactId = project.extensions.publish.artifactId ?: project.name
                        version = project.extensions.publish.version ?: project.version
                        if (version == "unspecified") {
                            throw new GradleException("Version unspecified")
                        }
                        from components.java
                    }
                }
            }
        }
    }

    static String fetchProperty(Project project, String propertyName) {
        try {
            return project.property(propertyName)
        } catch(MissingPropertyException ignored) {
            return null
        }
    }

    @CompileDynamic
    static String extractUsername(Project project) {
        project.extensions.publish.repository.username ?: fetchProperty(project, "publish.repository.username")
    }

    @CompileDynamic
    static String extractPassword(Project project) {
        project.extensions.publish.repository.password ?: fetchProperty(project, "publish.repository.password")
    }
}
